CREATE TABLE pacientes(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    id_carteirinha VARCHAR(50) UNIQUE
);

CREATE TABLE profissionais(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    telefone VARCHAR(15) NOT NULL,
    tipo VARCHAR(25) NOT NULL,

    CONSTRAINT check_tipo
    CHECK(tipo IN ('MEDICO', 'FISIOTERAPEUTA'))
);

CREATE TABLE agendamentos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id BIGINT NOT NULL,
    profissional_id BIGINT NOT NULL,
    data_agendamento TIMESTAMP NOT NULL,
    tipo_atendimento VARCHAR(10) NOT NULL,
    status VARCHAR(10) NOT NULL,
    motivo_cancelamento VARCHAR(255),

    CONSTRAINT fk_paciente_id
        FOREIGN KEY (paciente_id)
            REFERENCES pacientes(id),

    CONSTRAINT fk_profissional_id
        FOREIGN KEY (profissional_id)
            REFERENCES profissionais(id),

    CONSTRAINT check_tipo_atendimento
    CHECK ( tipo_atendimento IN ('INICIAL', 'RETORNO')),

    CONSTRAINT check_status
    CHECK ( status IN ('AGENDADO', 'CANCELADO'))
);